---
version: 0.2

env:
  variables:
    TFI_TF_ZIP: https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip

phases:
  install:
    commands:
      - curl -L "${TFI_TF_ZIP}" -o tf.zip && unzip tf.zip                       # install Terraform
  pre_build:
    commands:
      - export TF_VAR_tfi_codebuild_id="${CODEBUILD_BUILD_ID}"
      - ./terraform init -no-color -input=false                                 # init terraform
      - ./terraform plan -no-color -out=tfplan -input=false                     # plan terraform
  build:
    commands:
      - ./terraform apply -no-color -input=false tfplan                         # apply terraform
  post_build:
    commands:
      - ARTIFACT_LOCATION="s3://${TF_VAR_tfi_s3_bucket}/$(./terraform output build_date_ymd)/$(./terraform output build_date_hm)_$(./terraform output build_id)"
      - echo "ARTIFACT_LOCATION=${ARTIFACT_LOCATION}"
      - ./terraform output                                                      # save/display output information to file
      - ./terraform output | aws s3 cp - "${ARTIFACT_LOCATION}/terraform_output.log" || true
      - test -r $TF_LOG_PATH && aws s3 cp $TF_LOG_PATH "${ARTIFACT_LOCATION}/terraform.log" || true
      - |
        if [ "${TFI_DESTROY_AFTER_TEST}" = "true" ]; then                       # destroy resources
          ./terraform destroy -input=false -force
        fi
